"""
Markdown Reporter - Human-readable markdown report for sharing.
"""

from typing import Optional

from engine.models import ScanResult


class MarkdownReporter:
    """Report scan results as Markdown."""
    
    def report(self, result: ScanResult, output_file: Optional[str] = None):
        """
        Output scan results as Markdown.
        
        Args:
            result: Scan result to report
            output_file: Optional file to write output
        """
        lines = []
        
        # Header
        lines.append(f"# ClawGuard Scan Report: {result.skill_name}")
        lines.append("")
        
        # Risk badge
        risk_emoji = {
            "safe": "🟢",
            "low": "🟢",
            "medium": "🟡",
            "high": "🔴",
            "critical": "🔴",
        }.get(result.risk_level, "⚪")
        
        lines.append(f"**Risk Level:** {risk_emoji} {result.risk_level.upper()} ({result.risk_score}/100)")
        lines.append("")
        
        # Metadata
        lines.append("## Scan Details")
        lines.append("")
        lines.append(f"| Property | Value |")
        lines.append(f"|----------|-------|")
        lines.append(f"| Skill Path | `{result.skill_path}` |")
        lines.append(f"| Scan Time | {result.scan_timestamp} |")
        lines.append(f"| Duration | {result.scan_duration_seconds:.2f}s |")
        lines.append(f"| Files Scanned | {result.files_scanned} |")
        lines.append(f"| Lines Scanned | {result.total_lines_scanned} |")
        lines.append(f"| IOC Version | {result.ioc_database_version} |")
        lines.append("")
        
        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(result.summary)
        lines.append("")
        
        if not result.findings:
            lines.append("✅ **No security issues found.**")
        else:
            # Findings
            lines.append("## Findings")
            lines.append("")
            
            # Group by severity
            by_severity = {}
            for f in result.findings:
                by_severity.setdefault(f.severity, []).append(f)
            
            for severity in ["critical", "high", "medium", "warning", "info"]:
                if severity not in by_severity:
                    continue
                
                emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "warning": "⚠️", "info": "ℹ️"}.get(severity, "")
                lines.append(f"### {emoji} {severity.upper()}")
                lines.append("")
                
                for f in by_severity[severity]:
                    lines.append(f"#### [{f.id}] {f.description}")
                    lines.append("")
                    lines.append(f"- **File:** `{f.file_path}:{f.line_number}`")
                    lines.append(f"- **Category:** {f.category}")
                    lines.append(f"- **Confidence:** {f.confidence}")
                    lines.append(f"- **Code:** `{f.line_content}`")
                    lines.append(f"- **Action:** {f.recommendation}")
                    lines.append("")
        
        # Footer
        lines.append("---")
        lines.append("*Generated by ClawGuard Security Scanner*")
        
        md_output = "\n".join(lines)
        
        if output_file:
            with open(output_file, "w") as f:
                f.write(md_output)
            print(f"Report written to {output_file}")
        else:
            print(md_output)
